# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: windows-2019

variables:
  buildConfiguration: 'Release'

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'Visual Studio Enterprise(e9a8f3f9-354d-420f-94b3-108366cb911c)'
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: 'az vm start --resource-group vmTestWin10 --name testdev --subscription ''Visual Studio Enterprise'''
